[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "seekstorm-client-pure-py"
dynamic = ["version", "description"]
authors = [
    {name = "Wolf Garbe", email = "wolf.garbe@seekstorm.com"}
]
readme = "README.md"
license = {file = "LICENSE"}
requires-python = ">=3.8"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Internet :: WWW/HTTP",
]
dependencies = [
    "httpx >= 0.24.0",
]

[project.urls]
Documentation = "https://github.com/SeekStorm/seekstorm_client_pure_py#readme"
Source = "https://github.com/SeekStorm/seekstorm_client_pure_py"
Tracker = "https://github.com/SeekStorm/seekstorm_client_pure_py/issues"

[tool.flit.module]
name = "seekstorm_client"
